title: nbinlineai
description: AI prompts in JupyterLab notebooks
url: https://rahuldave.com
baseurl: /nbinlineai
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
